/**
 * Postinstall script — patches framer-motion type declarations.
 *
 * The motion-dom package (a dependency of framer-motion v12) ships without
 * TypeScript declarations, which breaks HTMLMotionProps (missing animate,
 * initial, exit, transition props). This script creates the missing .d.ts
 * file so that `tsc --noEmit` passes.
 */

const fs = require('fs');
const path = require('path');

function patchMotionDomTypes() {
  const motionDomDir = path.join(process.cwd(), 'node_modules', 'motion-dom', 'dist');
  const dtsPath = path.join(motionDomDir, 'index.d.ts');

  if (!fs.existsSync(motionDomDir)) {
    console.log('[postinstall] motion-dom not found, skipping type patch');
    return;
  }

  if (fs.existsSync(dtsPath)) {
    const content = fs.readFileSync(dtsPath, 'utf-8');
    if (content.includes('MotionNodeOptions')) {
      console.log('[postinstall] motion-dom types already patched');
      return;
    }
  }

  const declarations = `/**
 * Type declarations for motion-dom v12.
 * Auto-generated by postinstall script.
 */
export interface MotionNodeOptions {
  animate?: any; initial?: any; exit?: any; transition?: any;
  variants?: any; whileHover?: any; whileTap?: any; whileDrag?: any;
  whileFocus?: any; whileInView?: any; viewport?: any; drag?: any;
  dragConstraints?: any; dragElastic?: any; dragMomentum?: any;
  dragTransition?: any; dragSnapToOrigin?: any; dragPropagation?: any;
  dragControls?: any; onDragStart?: any; onDrag?: any; onDragEnd?: any;
  onDirectionLock?: any; layout?: any; layoutId?: any; layoutDependency?: any;
  layoutScroll?: any; layoutRoot?: boolean; onLayoutAnimationStart?: any;
  onLayoutAnimationComplete?: any; onLayoutMeasure?: any; custom?: any;
  inherit?: boolean; transformTemplate?: any; onAnimationStart?: any;
  onAnimationComplete?: any; onUpdate?: any; onViewportEnter?: any;
  onViewportLeave?: any;
}
export interface TransformProperties { x?: any; y?: any; z?: any; rotate?: any; rotateX?: any; rotateY?: any; rotateZ?: any; scale?: any; scaleX?: any; scaleY?: any; scaleZ?: any; skew?: any; skewX?: any; skewY?: any; originX?: any; originY?: any; originZ?: any; perspective?: any; }
export interface MotionValue<T = any> { get(): T; set(v: T): void; onChange(callback: (v: T) => void): () => void; }
export interface SVGPathProperties { pathLength?: any; pathOffset?: any; pathSpacing?: any; }
export type AnyResolvedKeyframe = string | number;
export type OnKeyframesResolved<V = any> = any;
export type KeyframeResolver<V = any> = any;
export type UnresolvedValueKeyframe = any;
export type ElementOrSelector = any;
export type DOMKeyframesDefinition = any;
export type AnimationOptions = any;
export type AnimationPlaybackOptions = any;
export type AnimationScope = any;
export type AnimationPlaybackControlsWithThen = any;
export type ValueAnimationTransition = any;
export type AnimationPlaybackControls = any;
export type EventInfo = any;
export type MotionValueEventCallbacks = any;
export type SpringOptions = any;
export type TransformOptions = any;
export type WillChange = any;
export type LegacyAnimationControls = any;
export type NodeGroup = any;
export type IProjectionNode = any;
export type ResolvedValues = Record<string, any>;
export type Feature = any;
export type PresenceContextProps = { id: string; isPresent: boolean; [key: string]: any };
export type Easing = any;
export type Transition = any;
export type Target = Record<string, any>;
export type TargetResolver = any;
export type Variant = any;
export type Variants = any;
export const animate: any;
export const animateMini: any;
export function addScaleCorrector(any: any): any;
export function resolveMotionValue(any: any): any;
export function startOptimizedAppearAnimation(any: any): any;
export const visualElementStore: any;
export const DelayedFunction: any;
export const FlatTree: any;
export const isValidMotionProp: any;
export const filterProps: any;
export const createMotionValue: any;
export const motionValue: any;
`;

  fs.writeFileSync(dtsPath, declarations, 'utf-8');
  console.log('[postinstall] Patched motion-dom type declarations');
}

patchMotionDomTypes();
